/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'construction' : null } |
  { 'lighting' : null } |
  { 'maintenance' : null } |
  { 'renovation' : null };
export interface ContactForm {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'photos' : Array<string>,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'featured' : boolean,
  'message' : string,
  'rating' : bigint,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProjectPhoto' : ActorMethod<[bigint, string], undefined>,
  'adminCreateProject' : ActorMethod<
    [string, string, string, Category, string, boolean, Array<string>],
    undefined
  >,
  'adminCreateTestimonial' : ActorMethod<
    [string, string, string, bigint, string, boolean],
    undefined
  >,
  'adminDeleteProject' : ActorMethod<[string, bigint], undefined>,
  'adminDeleteTestimonial' : ActorMethod<[string, bigint], undefined>,
  'adminGetAllContactForms' : ActorMethod<[string], Array<ContactForm>>,
  'adminUpdateProject' : ActorMethod<
    [string, bigint, string, string, Category, string, boolean, Array<string>],
    undefined
  >,
  'adminUpdateTestimonial' : ActorMethod<
    [string, bigint, string, string, bigint, string, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, string, Category, string, boolean, Array<string>],
    undefined
  >,
  'createTestimonial' : ActorMethod<
    [string, string, bigint, string, boolean],
    undefined
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getFeaturedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getProjectPhotos' : ActorMethod<[bigint], Array<string>>,
  'getProjectsByCategory' : ActorMethod<[Category], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, Category, string, boolean, Array<string>],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, bigint, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];